#=========================================================
# Purpose: Analyze a 16-bit adder VCD against the ripple-carry probabilistic model.
# This script reads a VCD file generated by the testbench, extracts the relevant signals,
# and performs a statistical analysis to validate the behavior of the adder against the expected
# probabilistic model of a ripple-carry adder with random inputs.
# Made by: Isaac Medina and Asher Milberg | Tufts University Department of Electrical and Computer Engineering
# Class of 2027
# Date Created: 4/16/2026
#=========================================================

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List

import numpy as np


WIDTH = 16
REQUIRED_SIGNAL_ALIASES = {
    "tb_A": ("tb_A", "A [15:0]"),
    "tb_B": ("tb_B", "B [15:0]"),
    "tb_Cin": ("tb_Cin", "Cin", "fa0.cin"),
    "dut_Sum": ("dut_Sum", "Sum [15:0]"),
    "dut_Cout": ("dut_Cout", "Cout"),
    "expected_total": ("expected_total",),
    "sample_idx": ("sample_idx",),
}


@dataclass
class Sample:
    sample_idx: int
    a: int
    b: int
    cin: int
    sum_value: int
    cout: int
    expected_total: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze a 16-bit adder VCD against the ripple-carry probabilistic model."
    )
    parser.add_argument(
        "--vcd",
        type=Path,
        default=Path("adder16_random.vcd"),
        help="Path to the VCD dump generated by tb.sv.",
    )
    parser.add_argument(
        "--num-samples",
        type=int,
        default=10000,
        help="Expected number of samples in the VCD.",
    )
    parser.add_argument(
        "--sigma-threshold",
        type=float,
        default=4.0,
        help="Maximum allowed absolute z-score for a metric to be considered valid.",
    )
    return parser.parse_args()


def carry_probability_profile(width: int, p_c0: float) -> List[float]:
    probabilities = [p_c0]
    for _ in range(width):
        next_probability = 0.25 + 0.5 * probabilities[-1]
        probabilities.append(next_probability)
    return probabilities


def print_probabilistic_model(width: int, p_c0: float) -> List[float]:
    profile = carry_probability_profile(width, p_c0)
    print("=== Probabilistic Model Analysis ===")
    print("For one full-adder stage with independent unbiased A_i and B_i:")
    print("P(C_{i+1}=1 | C_i=0) = 1/4")
    print("P(C_{i+1}=1 | C_i=1) = 3/4")
    print("P(S_i=1 | C_i=0) = 1/2")
    print("P(S_i=1 | C_i=1) = 1/2")
    print("Joint distribution when C_i=0:")
    print("  P(S_i=0, C_{i+1}=0) = 1/4")
    print("  P(S_i=1, C_{i+1}=0) = 1/2")
    print("  P(S_i=0, C_{i+1}=1) = 1/4")
    print("Joint distribution when C_i=1:")
    print("  P(S_i=1, C_{i+1}=0) = 1/4")
    print("  P(S_i=0, C_{i+1}=1) = 1/2")
    print("  P(S_i=1, C_{i+1}=1) = 1/4")
    print()
    print(f"Carry probability recursion: p_(i+1) = 1/4 + (1/2) * p_i, with p_0 = {p_c0:.4f}")
    print("Stage-by-stage carry probabilities:")
    for stage, probability in enumerate(profile):
        label = "C_in" if stage == 0 else f"C_{stage}"
        print(f"  {label}: P= {probability:.6f}")
    print("Implication for unbiased random inputs with P(C_in=1)=0.5:")
    if math.isclose(p_c0, 0.5, abs_tol=1e-12):
        print("  The carry process is already at steady state, so every carry bit is unbiased.")
        print("  Therefore every sum bit is also unbiased: P(S_i = 1) = 0.5 for all i.")
    print()
    return profile


def parse_vcd_definitions(lines: Iterable[str]) -> tuple[Dict[str, str], int]:
    scopes: List[str] = []
    code_to_name: Dict[str, str] = {}
    line_count = 0

    for raw_line in lines:
        line_count += 1
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("$scope"):
            tokens = line.split()
            scopes.append(tokens[2])
        elif line.startswith("$upscope"):
            if scopes:
                scopes.pop()
        elif line.startswith("$var"):
            tokens = line.split()
            code = tokens[3]
            reference = " ".join(tokens[4:-1])
            full_name = ".".join(scopes + [reference]) if scopes else reference
            code_to_name[code] = full_name
        elif line.startswith("$enddefinitions"):
            break

    return code_to_name, line_count


def resolve_signal_codes(code_to_name: Dict[str, str]) -> Dict[str, str]:
    resolved: Dict[str, str] = {}
    for required, aliases in REQUIRED_SIGNAL_ALIASES.items():
        for code, full_name in code_to_name.items():
            base_name = full_name.split(".")[-1]
            for alias in aliases:
                if base_name == alias or base_name.startswith(f"{alias} ") or full_name.endswith(alias):
                    resolved[required] = code
                    break
            if required in resolved:
                break
        if required not in resolved:
            available = ", ".join(sorted(code_to_name.values()))
            raise ValueError(
                f"Could not find required signal '{required}' in VCD.\nAvailable signals: {available}"
            )
    return resolved


def value_to_int(value: str) -> int | None:
    cleaned = value.strip().lower()
    if not cleaned or any(char in cleaned for char in "xz"):
        return None
    if cleaned[0] in "01":
        return int(cleaned, 2)
    return None


def snapshot_if_complete(
    current_values: Dict[str, str],
    signal_codes: Dict[str, str],
    snapshots: Dict[int, Sample],
) -> None:
    try:
        raw_values = {name: current_values[code] for name, code in signal_codes.items()}
    except KeyError:
        return

    decoded = {name: value_to_int(raw) for name, raw in raw_values.items()}
    if any(value is None for value in decoded.values()):
        return

    sample_idx = int(decoded["sample_idx"])
    if sample_idx == (1 << 32) - 1:
        sample_idx = -1
    if sample_idx < 0:
        return

    snapshots[sample_idx] = Sample(
        sample_idx=sample_idx,
        a=int(decoded["tb_A"]),
        b=int(decoded["tb_B"]),
        cin=int(decoded["tb_Cin"]),
        sum_value=int(decoded["dut_Sum"]),
        cout=int(decoded["dut_Cout"]),
        expected_total=int(decoded["expected_total"]),
    )


def parse_vcd_samples(vcd_path: Path) -> List[Sample]:
    with vcd_path.open("r", encoding="ascii", errors="replace") as handle:
        all_lines = handle.readlines()

    code_to_name, definition_end_line = parse_vcd_definitions(all_lines)
    signal_codes = resolve_signal_codes(code_to_name)

    current_values: Dict[str, str] = {}
    snapshots: Dict[int, Sample] = {}

    for raw_line in all_lines[definition_end_line:]:
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("#"):
            snapshot_if_complete(current_values, signal_codes, snapshots)
            continue

        if line[0] in "01xz":
            current_values[line[1:]] = line[0]
            continue

        if line[0] == "b":
            vector_value, code = line[1:].split()
            current_values[code] = vector_value

    snapshot_if_complete(current_values, signal_codes, snapshots)
    return [snapshots[index] for index in sorted(snapshots)]


def reconstruct_internal_carries(a_value: int, b_value: int, cin: int, width: int) -> np.ndarray:
    carries = np.zeros(width + 1, dtype=np.int8)
    carries[0] = cin
    for bit in range(width):
        a_bit = (a_value >> bit) & 1
        b_bit = (b_value >> bit) & 1
        carries[bit + 1] = (a_bit & b_bit) | (a_bit & carries[bit]) | (b_bit & carries[bit])
    return carries


def extract_bit_matrix(values: np.ndarray, width: int) -> np.ndarray:
    return ((values[:, None] >> np.arange(width)) & 1).astype(np.int8)


def bernoulli_z_score(observed_probability: float, expected_probability: float, trials: int) -> float:
    if trials <= 0:
        return 0.0
    variance = expected_probability * (1.0 - expected_probability)
    if variance == 0.0:
        return 0.0
    sigma = math.sqrt(variance / trials)
    return (observed_probability - expected_probability) / sigma


def analyze_samples(samples: List[Sample], sigma_threshold: float) -> bool:
    if not samples:
        raise ValueError("No complete samples were recovered from the VCD.")

    a_values = np.array([sample.a for sample in samples], dtype=np.uint32)
    b_values = np.array([sample.b for sample in samples], dtype=np.uint32)
    cin_values = np.array([sample.cin for sample in samples], dtype=np.uint8)
    sum_values = np.array([sample.sum_value for sample in samples], dtype=np.uint32)
    cout_values = np.array([sample.cout for sample in samples], dtype=np.uint8)
    expected_totals = np.array([sample.expected_total for sample in samples], dtype=np.uint32)

    recomputed_totals = a_values.astype(np.uint32) + b_values.astype(np.uint32) + cin_values.astype(np.uint32)
    dut_totals = (cout_values.astype(np.uint32) << WIDTH) | sum_values.astype(np.uint32)
    functional_mismatches = int(np.count_nonzero(dut_totals != recomputed_totals))
    expected_mismatches = int(np.count_nonzero(expected_totals != recomputed_totals))

    a_bits = extract_bit_matrix(a_values, WIDTH)
    b_bits = extract_bit_matrix(b_values, WIDTH)
    sum_bits = extract_bit_matrix(sum_values, WIDTH)

    carry_matrix = np.array(
        [reconstruct_internal_carries(sample.a, sample.b, sample.cin, WIDTH) for sample in samples],
        dtype=np.int8,
    )

    theoretical_carry_profile = np.array(carry_probability_profile(WIDTH, 0.5))
    empirical_a_probs = a_bits.mean(axis=0)
    empirical_b_probs = b_bits.mean(axis=0)
    empirical_sum_probs = sum_bits.mean(axis=0)
    empirical_carry_probs = carry_matrix.mean(axis=0)

    print("=== Dataset Summary From VCD ===")
    print(f"Recovered samples: {len(samples)}")
    print(f"Functional mismatches between DUT output and software model: {functional_mismatches}")
    print(f"Mismatches between VCD expected_total and software model: {expected_mismatches}")
    print()

    print("=== Input Randomness Sanity Check ===")
    print(f"P(Cin=1): empirical={cin_values.mean():.4f}, expected=0.5000")
    print(
        f"Mean P(A_i=1): empirical={empirical_a_probs.mean():.4f}, expected=0.5000, "
        f"max bit deviation={np.max(np.abs(empirical_a_probs - 0.5)):.4f}"
    )
    print(
        f"Mean P(B_i=1): empirical={empirical_b_probs.mean():.4f}, expected=0.5000, "
        f"max bit deviation={np.max(np.abs(empirical_b_probs - 0.5)):.4f}"
    )
    print()

    print("=== Sum-Bit Validation ===")
    max_sum_z = 0.0
    for bit in range(WIDTH):
        observed = float(empirical_sum_probs[bit])
        z_score = bernoulli_z_score(observed, 0.5, len(samples))
        max_sum_z = max(max_sum_z, abs(z_score))
        print(f"Bit {bit:2d}: empirical={observed:.4f}, expected=0.5000, z={z_score:+.2f}")
    print()

    print("=== Carry-State Validation ===")
    max_carry_z = 0.0
    for stage in range(WIDTH + 1):
        observed = float(empirical_carry_probs[stage])
        expected = float(theoretical_carry_profile[stage])
        z_score = bernoulli_z_score(observed, expected, len(samples))
        max_carry_z = max(max_carry_z, abs(z_score))
        label = "Cin" if stage == 0 else f"C{stage}"
        print(f"{label:>3}: empirical={observed:.4f}, expected={expected:.4f}, z={z_score:+.2f}")
    print()

    c_in = carry_matrix[:, :-1]
    c_out = carry_matrix[:, 1:]
    mask_c0 = c_in == 0
    mask_c1 = c_in == 1
    n_c0 = int(mask_c0.sum())
    n_c1 = int(mask_c1.sum())

    p_cout_given_c0 = float(c_out[mask_c0].mean()) if n_c0 else float("nan")
    p_cout_given_c1 = float(c_out[mask_c1].mean()) if n_c1 else float("nan")
    z_c0 = bernoulli_z_score(p_cout_given_c0, 0.25, n_c0)
    z_c1 = bernoulli_z_score(p_cout_given_c1, 0.75, n_c1)

    print("=== Conditional Carry Transition Validation ===")
    print(f"P(C_out=1 | C_in=0): empirical={p_cout_given_c0:.4f}, expected=0.2500, z={z_c0:+.2f}, N={n_c0}")
    print(f"P(C_out=1 | C_in=1): empirical={p_cout_given_c1:.4f}, expected=0.7500, z={z_c1:+.2f}, N={n_c1}")
    print()

    validity_checks = [
        functional_mismatches == 0,
        expected_mismatches == 0,
        max_sum_z <= sigma_threshold,
        max_carry_z <= sigma_threshold,
        abs(z_c0) <= sigma_threshold,
        abs(z_c1) <= sigma_threshold,
    ]
    model_valid = all(validity_checks)

    print("=== Final Verdict ===")
    if model_valid:
        print(
            "The VCD data is consistent with the ripple-carry probabilistic model "
            f"within a {sigma_threshold:.1f} sigma acceptance band."
        )
    else:
        print(
            "The VCD data does not fully validate the ripple-carry probabilistic model "
            f"under the current {sigma_threshold:.1f} sigma acceptance band."
        )

    return model_valid


def main() -> None:
    args = parse_args()
    print_probabilistic_model(WIDTH, 0.5)
    samples = parse_vcd_samples(args.vcd)
    if len(samples) != args.num_samples:
        print(
            f"Warning: expected {args.num_samples} samples, but recovered {len(samples)} complete samples "
            f"from {args.vcd}."
        )
        print()
    analyze_samples(samples, args.sigma_threshold)


if __name__ == "__main__":
    main()
