#=========================================================
# Purpose: Analyze a 16-bit adder VCD against the ripple-carry probabilistic model.
# This script reads a VCD file generated by the testbench, extracts the relevant signals,
# and performs a statistical analysis to validate the behavior of the adder against the expected
# probabilistic model of a ripple-carry adder with random inputs.
# Made by: Isaac Medina and Asher Milberg | Tufts University Department of Electrical and Computer Engineering
# Class of 2027
# Date Created: 4/16/2026
#=========================================================

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence

import numpy as np


WIDTH = 16
SCRIPT_DIR = Path(__file__).resolve().parent
REQUIRED_SIGNAL_ALIASES = {
    "tb_A": ("tb_A", "A [15:0]"),
    "tb_B": ("tb_B", "B [15:0]"),
    "tb_Cin": ("tb_Cin", "Cin", "fa0.cin"),
    "dut_Sum": ("dut_Sum", "Sum [15:0]"),
    "dut_Cout": ("dut_Cout", "Cout"),
    "expected_total": ("expected_total",),
    "sample_idx": ("sample_idx",),
}


@dataclass
class Sample:
    sample_idx: int
    a: int
    b: int
    cin: int
    sum_value: int
    cout: int
    expected_total: int


@dataclass
class AnalysisResults:
    sample_count: int
    functional_mismatches: int
    expected_mismatches: int
    a_values: np.ndarray
    b_values: np.ndarray
    cin_values: np.ndarray
    sum_values: np.ndarray
    dut_totals: np.ndarray
    empirical_a_probs: np.ndarray
    empirical_b_probs: np.ndarray
    empirical_sum_probs: np.ndarray
    empirical_carry_probs: np.ndarray
    theoretical_sum_probs: np.ndarray
    theoretical_carry_probs: np.ndarray
    sum_absolute_errors: np.ndarray
    carry_absolute_errors: np.ndarray
    sum_z_scores: np.ndarray
    carry_z_scores: np.ndarray
    p_cin_empirical: float
    p_cout_given_c0: float
    p_cout_given_c1: float
    z_c0: float
    z_c1: float
    n_c0: int
    n_c1: int
    model_valid: bool
    sigma_threshold: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze a 16-bit adder VCD against the ripple-carry probabilistic model."
    )
    parser.add_argument(
        "--vcd",
        type=Path,
        default=Path("adder16_random.vcd"),
        help="Path to the VCD dump generated by tb.sv.",
    )
    parser.add_argument(
        "--num-samples",
        type=int,
        default=10000,
        help="Expected number of samples in the VCD.",
    )
    parser.add_argument(
        "--sigma-threshold",
        type=float,
        default=4.0,
        help="Maximum allowed absolute z-score for a metric to be considered valid.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("analysis_outputs"),
        help="Directory where tables and SVG plots will be written.",
    )
    return parser.parse_args()


def carry_probability_profile(width: int, p_c0: float) -> List[float]:
    probabilities = [p_c0]
    for _ in range(width):
        next_probability = 0.25 + 0.5 * probabilities[-1]
        probabilities.append(next_probability)
    return probabilities


def print_probabilistic_model(width: int, p_c0: float) -> List[float]:
    profile = carry_probability_profile(width, p_c0)
    print("=== Probabilistic Model Analysis ===")
    print("For one full-adder stage with independent unbiased A_i and B_i:")
    print("P(C_{i+1}=1 | C_i=0) = 1/4")
    print("P(C_{i+1}=1 | C_i=1) = 3/4")
    print("P(S_i=1 | C_i=0) = 1/2")
    print("P(S_i=1 | C_i=1) = 1/2")
    print("Joint distribution when C_i=0:")
    print("  P(S_i=0, C_{i+1}=0) = 1/4")
    print("  P(S_i=1, C_{i+1}=0) = 1/2")
    print("  P(S_i=0, C_{i+1}=1) = 1/4")
    print("Joint distribution when C_i=1:")
    print("  P(S_i=1, C_{i+1}=0) = 1/4")
    print("  P(S_i=0, C_{i+1}=1) = 1/2")
    print("  P(S_i=1, C_{i+1}=1) = 1/4")
    print()
    print(f"Carry probability recursion: p_(i+1) = 1/4 + (1/2) * p_i, with p_0 = {p_c0:.4f}")
    print("Stage-by-stage carry probabilities:")
    for stage, probability in enumerate(profile):
        label = "C_in" if stage == 0 else f"C_{stage}"
        print(f"  {label}: P= {probability:.6f}")
    print("Implication for unbiased random inputs with P(C_in=1)=0.5:")
    if math.isclose(p_c0, 0.5, abs_tol=1e-12):
        print("  The carry process is already at steady state, so every carry bit is unbiased.")
        print("  Therefore every sum bit is also unbiased: P(S_i = 1) = 0.5 for all i.")
    print()
    return profile


def parse_vcd_definitions(lines: Iterable[str]) -> tuple[Dict[str, str], int]:
    scopes: List[str] = []
    code_to_name: Dict[str, str] = {}
    line_count = 0

    for raw_line in lines:
        line_count += 1
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("$scope"):
            tokens = line.split()
            scopes.append(tokens[2])
        elif line.startswith("$upscope"):
            if scopes:
                scopes.pop()
        elif line.startswith("$var"):
            tokens = line.split()
            code = tokens[3]
            reference = " ".join(tokens[4:-1])
            full_name = ".".join(scopes + [reference]) if scopes else reference
            code_to_name[code] = full_name
        elif line.startswith("$enddefinitions"):
            break

    return code_to_name, line_count


def resolve_signal_codes(code_to_name: Dict[str, str]) -> Dict[str, str]:
    resolved: Dict[str, str] = {}
    for required, aliases in REQUIRED_SIGNAL_ALIASES.items():
        for code, full_name in code_to_name.items():
            base_name = full_name.split(".")[-1]
            for alias in aliases:
                if base_name == alias or base_name.startswith(f"{alias} ") or full_name.endswith(alias):
                    resolved[required] = code
                    break
            if required in resolved:
                break
        if required not in resolved:
            available = ", ".join(sorted(code_to_name.values()))
            raise ValueError(
                f"Could not find required signal '{required}' in VCD.\nAvailable signals: {available}"
            )
    return resolved


def value_to_int(value: str) -> int | None:
    cleaned = value.strip().lower()
    if not cleaned or any(char in cleaned for char in "xz"):
        return None
    if cleaned[0] in "01":
        return int(cleaned, 2)
    return None


def snapshot_if_complete(
    current_values: Dict[str, str],
    signal_codes: Dict[str, str],
    snapshots: Dict[int, Sample],
) -> None:
    try:
        raw_values = {name: current_values[code] for name, code in signal_codes.items()}
    except KeyError:
        return

    decoded = {name: value_to_int(raw) for name, raw in raw_values.items()}
    if any(value is None for value in decoded.values()):
        return

    sample_idx = int(decoded["sample_idx"])
    if sample_idx == (1 << 32) - 1:
        sample_idx = -1
    if sample_idx < 0:
        return

    snapshots[sample_idx] = Sample(
        sample_idx=sample_idx,
        a=int(decoded["tb_A"]),
        b=int(decoded["tb_B"]),
        cin=int(decoded["tb_Cin"]),
        sum_value=int(decoded["dut_Sum"]),
        cout=int(decoded["dut_Cout"]),
        expected_total=int(decoded["expected_total"]),
    )


def parse_vcd_samples(vcd_path: Path) -> List[Sample]:
    with vcd_path.open("r", encoding="ascii", errors="replace") as handle:
        all_lines = handle.readlines()

    code_to_name, definition_end_line = parse_vcd_definitions(all_lines)
    signal_codes = resolve_signal_codes(code_to_name)

    current_values: Dict[str, str] = {}
    snapshots: Dict[int, Sample] = {}

    for raw_line in all_lines[definition_end_line:]:
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("#"):
            snapshot_if_complete(current_values, signal_codes, snapshots)
            continue

        if line[0] in "01xz":
            current_values[line[1:]] = line[0]
            continue

        if line[0] == "b":
            vector_value, code = line[1:].split()
            current_values[code] = vector_value

    snapshot_if_complete(current_values, signal_codes, snapshots)
    return [snapshots[index] for index in sorted(snapshots)]


def reconstruct_internal_carries(a_value: int, b_value: int, cin: int, width: int) -> np.ndarray:
    carries = np.zeros(width + 1, dtype=np.int8)
    carries[0] = cin
    for bit in range(width):
        a_bit = (a_value >> bit) & 1
        b_bit = (b_value >> bit) & 1
        carries[bit + 1] = (a_bit & b_bit) | (a_bit & carries[bit]) | (b_bit & carries[bit])
    return carries


def extract_bit_matrix(values: np.ndarray, width: int) -> np.ndarray:
    return ((values[:, None] >> np.arange(width)) & 1).astype(np.int8)


def bernoulli_z_score(observed_probability: float, expected_probability: float, trials: int) -> float:
    if trials <= 0:
        return 0.0
    variance = expected_probability * (1.0 - expected_probability)
    if variance == 0.0:
        return 0.0
    sigma = math.sqrt(variance / trials)
    return (observed_probability - expected_probability) / sigma


def resolve_vcd_path(vcd_path: Path) -> Path:
    candidate_paths = []
    if vcd_path.is_absolute():
        candidate_paths.append(vcd_path)
    else:
        candidate_paths.append(SCRIPT_DIR / vcd_path)
        candidate_paths.append(Path.cwd() / vcd_path)

    for candidate in candidate_paths:
        if candidate.exists():
            return candidate.resolve()

    searched_locations = "\n".join(f"  - {candidate}" for candidate in candidate_paths)
    raise FileNotFoundError(
        f"Could not find the VCD file '{vcd_path}'.\n"
        "Looked in:\n"
        f"{searched_locations}\n"
        "Run the testbench first, or pass --vcd /full/path/to/adder16_random.vcd."
    )


def write_csv_table(output_path: Path, header: Sequence[str], rows: Sequence[Sequence[object]]) -> None:
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def svg_header(width: int, height: int) -> List[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#fcfcf8"/>',
    ]


def write_svg(output_path: Path, lines: Sequence[str]) -> None:
    output_path.write_text("\n".join([*lines, "</svg>"]) + "\n", encoding="utf-8")


def create_line_plot_svg(
    output_path: Path,
    title: str,
    x_labels: Sequence[str],
    expected_values: Sequence[float],
    empirical_values: Sequence[float],
    y_label: str,
    expected_color: str = "#1f5aa6",
    empirical_color: str = "#cc5500",
) -> None:
    width = 1100
    height = 620
    margin_left = 90
    margin_right = 30
    margin_top = 80
    margin_bottom = 120
    plot_width = width - margin_left - margin_right
    plot_height = height - margin_top - margin_bottom

    def x_coord(index: int) -> float:
        if len(x_labels) == 1:
            return margin_left + plot_width / 2
        return margin_left + index * plot_width / (len(x_labels) - 1)

    def y_coord(value: float) -> float:
        value = max(0.0, min(1.0, value))
        return margin_top + (1.0 - value) * plot_height

    svg_lines = svg_header(width, height)
    svg_lines.extend(
        [
            f'<text x="{width / 2}" y="36" text-anchor="middle" font-size="24" fill="#1f1f1f">{title}</text>',
            f'<text x="{width / 2}" y="{height - 20}" text-anchor="middle" font-size="18" fill="#1f1f1f">Bit / Stage</text>',
            f'<text x="28" y="{height / 2}" text-anchor="middle" font-size="18" fill="#1f1f1f" '
            'transform="rotate(-90 28,310)">{}</text>'.format(y_label),
            f'<line x1="{margin_left}" y1="{margin_top}" x2="{margin_left}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
            f'<line x1="{margin_left}" y1="{margin_top + plot_height}" x2="{margin_left + plot_width}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
        ]
    )

    for tick in np.linspace(0.0, 1.0, 6):
        y = y_coord(float(tick))
        svg_lines.append(
            f'<line x1="{margin_left}" y1="{y:.2f}" x2="{margin_left + plot_width}" y2="{y:.2f}" '
            'stroke="#dddddd" stroke-width="1"/>'
        )
        svg_lines.append(
            f'<text x="{margin_left - 10}" y="{y + 5:.2f}" text-anchor="end" font-size="14" fill="#444">{tick:.1f}</text>'
        )

    for index, label in enumerate(x_labels):
        x = x_coord(index)
        svg_lines.append(
            f'<line x1="{x:.2f}" y1="{margin_top + plot_height}" x2="{x:.2f}" y2="{margin_top + plot_height + 6}" '
            'stroke="#222" stroke-width="1"/>'
        )
        svg_lines.append(
            f'<text x="{x:.2f}" y="{margin_top + plot_height + 24}" text-anchor="middle" font-size="12" fill="#444">{label}</text>'
        )

    def polyline(values: Sequence[float], color: str) -> str:
        points = " ".join(f"{x_coord(i):.2f},{y_coord(v):.2f}" for i, v in enumerate(values))
        return f'<polyline fill="none" stroke="{color}" stroke-width="3" points="{points}"/>'

    svg_lines.append(polyline(expected_values, expected_color))
    svg_lines.append(polyline(empirical_values, empirical_color))

    for index, value in enumerate(expected_values):
        svg_lines.append(
            f'<circle cx="{x_coord(index):.2f}" cy="{y_coord(value):.2f}" r="4" fill="{expected_color}"/>'
        )
    for index, value in enumerate(empirical_values):
        svg_lines.append(
            f'<circle cx="{x_coord(index):.2f}" cy="{y_coord(value):.2f}" r="4" fill="{empirical_color}"/>'
        )

    legend_x = width - 280
    legend_y = 55
    svg_lines.extend(
        [
            f'<rect x="{legend_x}" y="{legend_y}" width="220" height="54" fill="#ffffff" stroke="#cccccc"/>',
            f'<line x1="{legend_x + 16}" y1="{legend_y + 18}" x2="{legend_x + 56}" y2="{legend_y + 18}" stroke="{expected_color}" stroke-width="3"/>',
            f'<text x="{legend_x + 66}" y="{legend_y + 23}" font-size="15" fill="#222">Theoretical model</text>',
            f'<line x1="{legend_x + 16}" y1="{legend_y + 38}" x2="{legend_x + 56}" y2="{legend_y + 38}" stroke="{empirical_color}" stroke-width="3"/>',
            f'<text x="{legend_x + 66}" y="{legend_y + 43}" font-size="15" fill="#222">Empirical VCD data</text>',
        ]
    )

    write_svg(output_path, svg_lines)


def create_bar_plot_svg(
    output_path: Path,
    title: str,
    labels: Sequence[str],
    expected_values: Sequence[float],
    empirical_values: Sequence[float],
    y_label: str,
) -> None:
    width = 900
    height = 620
    margin_left = 90
    margin_right = 30
    margin_top = 80
    margin_bottom = 120
    plot_width = width - margin_left - margin_right
    plot_height = height - margin_top - margin_bottom
    group_width = plot_width / max(len(labels), 1)
    bar_width = group_width * 0.28

    def y_coord(value: float) -> float:
        value = max(0.0, min(1.0, value))
        return margin_top + (1.0 - value) * plot_height

    svg_lines = svg_header(width, height)
    svg_lines.extend(
        [
            f'<text x="{width / 2}" y="36" text-anchor="middle" font-size="24" fill="#1f1f1f">{title}</text>',
            f'<text x="{width / 2}" y="{height - 20}" text-anchor="middle" font-size="18" fill="#1f1f1f">Condition</text>',
            f'<text x="28" y="{height / 2}" text-anchor="middle" font-size="18" fill="#1f1f1f" '
            'transform="rotate(-90 28,310)">{}</text>'.format(y_label),
            f'<line x1="{margin_left}" y1="{margin_top}" x2="{margin_left}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
            f'<line x1="{margin_left}" y1="{margin_top + plot_height}" x2="{margin_left + plot_width}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
        ]
    )

    for tick in np.linspace(0.0, 1.0, 6):
        y = y_coord(float(tick))
        svg_lines.append(
            f'<line x1="{margin_left}" y1="{y:.2f}" x2="{margin_left + plot_width}" y2="{y:.2f}" stroke="#dddddd" stroke-width="1"/>'
        )
        svg_lines.append(
            f'<text x="{margin_left - 10}" y="{y + 5:.2f}" text-anchor="end" font-size="14" fill="#444">{tick:.1f}</text>'
        )

    for index, label in enumerate(labels):
        center_x = margin_left + group_width * (index + 0.5)
        expected_x = center_x - bar_width - 6
        empirical_x = center_x + 6
        expected_top = y_coord(expected_values[index])
        empirical_top = y_coord(empirical_values[index])
        baseline = margin_top + plot_height

        svg_lines.append(
            f'<rect x="{expected_x:.2f}" y="{expected_top:.2f}" width="{bar_width:.2f}" '
            f'height="{baseline - expected_top:.2f}" fill="#1f5aa6"/>'
        )
        svg_lines.append(
            f'<rect x="{empirical_x:.2f}" y="{empirical_top:.2f}" width="{bar_width:.2f}" '
            f'height="{baseline - empirical_top:.2f}" fill="#cc5500"/>'
        )
        svg_lines.append(
            f'<text x="{center_x:.2f}" y="{baseline + 24}" text-anchor="middle" font-size="14" fill="#444">{label}</text>'
        )
        svg_lines.append(
            f'<text x="{expected_x + bar_width / 2:.2f}" y="{expected_top - 8:.2f}" text-anchor="middle" font-size="12" fill="#1f5aa6">{expected_values[index]:.3f}</text>'
        )
        svg_lines.append(
            f'<text x="{empirical_x + bar_width / 2:.2f}" y="{empirical_top - 8:.2f}" text-anchor="middle" font-size="12" fill="#cc5500">{empirical_values[index]:.3f}</text>'
        )

    legend_x = width - 270
    legend_y = 55
    svg_lines.extend(
        [
            f'<rect x="{legend_x}" y="{legend_y}" width="210" height="54" fill="#ffffff" stroke="#cccccc"/>',
            f'<rect x="{legend_x + 16}" y="{legend_y + 10}" width="18" height="18" fill="#1f5aa6"/>',
            f'<text x="{legend_x + 44}" y="{legend_y + 24}" font-size="15" fill="#222">Theoretical model</text>',
            f'<rect x="{legend_x + 16}" y="{legend_y + 31}" width="18" height="18" fill="#cc5500"/>',
            f'<text x="{legend_x + 44}" y="{legend_y + 45}" font-size="15" fill="#222">Empirical VCD data</text>',
        ]
    )

    write_svg(output_path, svg_lines)


def create_single_series_bar_plot_svg(
    output_path: Path,
    title: str,
    labels: Sequence[str],
    values: Sequence[float],
    y_label: str,
    bar_color: str = "#b94e48",
) -> None:
    width = 1100
    height = 620
    margin_left = 90
    margin_right = 30
    margin_top = 80
    margin_bottom = 120
    plot_width = width - margin_left - margin_right
    plot_height = height - margin_top - margin_bottom
    group_width = plot_width / max(len(labels), 1)
    bar_width = group_width * 0.6
    max_value = max(max(values), 1e-6)

    def y_coord(value: float) -> float:
        value = max(0.0, value)
        return margin_top + (1.0 - (value / max_value)) * plot_height

    svg_lines = svg_header(width, height)
    svg_lines.extend(
        [
            f'<text x="{width / 2}" y="36" text-anchor="middle" font-size="24" fill="#1f1f1f">{title}</text>',
            f'<text x="{width / 2}" y="{height - 20}" text-anchor="middle" font-size="18" fill="#1f1f1f">Bit / Stage</text>',
            f'<text x="28" y="{height / 2}" text-anchor="middle" font-size="18" fill="#1f1f1f" '
            'transform="rotate(-90 28,310)">{}</text>'.format(y_label),
            f'<line x1="{margin_left}" y1="{margin_top}" x2="{margin_left}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
            f'<line x1="{margin_left}" y1="{margin_top + plot_height}" x2="{margin_left + plot_width}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
        ]
    )

    for tick in np.linspace(0.0, max_value, 6):
        y = y_coord(float(tick))
        svg_lines.append(
            f'<line x1="{margin_left}" y1="{y:.2f}" x2="{margin_left + plot_width}" y2="{y:.2f}" stroke="#dddddd" stroke-width="1"/>'
        )
        svg_lines.append(
            f'<text x="{margin_left - 10}" y="{y + 5:.2f}" text-anchor="end" font-size="14" fill="#444">{tick:.4f}</text>'
        )

    baseline = margin_top + plot_height
    for index, label in enumerate(labels):
        center_x = margin_left + group_width * (index + 0.5)
        x = center_x - bar_width / 2
        top = y_coord(values[index])
        svg_lines.append(
            f'<rect x="{x:.2f}" y="{top:.2f}" width="{bar_width:.2f}" height="{baseline - top:.2f}" fill="{bar_color}"/>'
        )
        svg_lines.append(
            f'<text x="{center_x:.2f}" y="{baseline + 24}" text-anchor="middle" font-size="12" fill="#444">{label}</text>'
        )
        svg_lines.append(
            f'<text x="{center_x:.2f}" y="{top - 8:.2f}" text-anchor="middle" font-size="11" fill="{bar_color}">{values[index]:.4f}</text>'
        )

    write_svg(output_path, svg_lines)


def create_histogram_svg(
    output_path: Path,
    title: str,
    data: np.ndarray,
    bins: int,
    x_label: str,
    bar_color: str = "#5f8f3e",
) -> None:
    width = 1100
    height = 620
    margin_left = 90
    margin_right = 30
    margin_top = 80
    margin_bottom = 120
    plot_width = width - margin_left - margin_right
    plot_height = height - margin_top - margin_bottom

    counts, bin_edges = np.histogram(data.astype(np.float64), bins=bins)
    max_count = max(int(counts.max()), 1)
    bar_width = plot_width / max(len(counts), 1)

    def y_coord(value: float) -> float:
        return margin_top + (1.0 - (value / max_count)) * plot_height

    svg_lines = svg_header(width, height)
    svg_lines.extend(
        [
            f'<text x="{width / 2}" y="36" text-anchor="middle" font-size="24" fill="#1f1f1f">{title}</text>',
            f'<text x="{width / 2}" y="{height - 20}" text-anchor="middle" font-size="18" fill="#1f1f1f">{x_label}</text>',
            f'<text x="28" y="{height / 2}" text-anchor="middle" font-size="18" fill="#1f1f1f" '
            'transform="rotate(-90 28,310)">Count</text>',
            f'<line x1="{margin_left}" y1="{margin_top}" x2="{margin_left}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
            f'<line x1="{margin_left}" y1="{margin_top + plot_height}" x2="{margin_left + plot_width}" y2="{margin_top + plot_height}" stroke="#222" stroke-width="2"/>',
        ]
    )

    for tick in np.linspace(0.0, max_count, 6):
        y = y_coord(float(tick))
        svg_lines.append(
            f'<line x1="{margin_left}" y1="{y:.2f}" x2="{margin_left + plot_width}" y2="{y:.2f}" stroke="#dddddd" stroke-width="1"/>'
        )
        svg_lines.append(
            f'<text x="{margin_left - 10}" y="{y + 5:.2f}" text-anchor="end" font-size="14" fill="#444">{int(round(tick))}</text>'
        )

    baseline = margin_top + plot_height
    for index, count in enumerate(counts):
        x = margin_left + index * bar_width
        top = y_coord(float(count))
        svg_lines.append(
            f'<rect x="{x + 1:.2f}" y="{top:.2f}" width="{max(bar_width - 2, 1):.2f}" height="{baseline - top:.2f}" fill="{bar_color}"/>'
        )

    tick_count = min(8, len(bin_edges))
    tick_indices = np.linspace(0, len(bin_edges) - 1, tick_count, dtype=int)
    for tick_index in np.unique(tick_indices):
        fraction = tick_index / max(len(bin_edges) - 1, 1)
        x = margin_left + fraction * plot_width
        label = f"{bin_edges[tick_index]:.0f}"
        svg_lines.append(
            f'<line x1="{x:.2f}" y1="{baseline}" x2="{x:.2f}" y2="{baseline + 6}" stroke="#222" stroke-width="1"/>'
        )
        svg_lines.append(
            f'<text x="{x:.2f}" y="{baseline + 24}" text-anchor="middle" font-size="12" fill="#444">{label}</text>'
        )

    write_svg(output_path, svg_lines)


def write_analysis_outputs(output_dir: Path, results: AnalysisResults) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    bit_labels = [str(bit) for bit in range(WIDTH)]
    carry_labels = ["Cin", *[f"C{stage}" for stage in range(1, WIDTH + 1)]]

    write_csv_table(
        output_dir / "sum_bit_comparison.csv",
        ["bit", "theoretical_probability", "empirical_probability", "z_score"],
        [
            [bit, f"{results.theoretical_sum_probs[bit]:.6f}", f"{results.empirical_sum_probs[bit]:.6f}", f"{results.sum_z_scores[bit]:.6f}"]
            for bit in range(WIDTH)
        ],
    )
    write_csv_table(
        output_dir / "carry_probability_comparison.csv",
        ["stage", "theoretical_probability", "empirical_probability", "z_score"],
        [
            [
                carry_labels[stage],
                f"{results.theoretical_carry_probs[stage]:.6f}",
                f"{results.empirical_carry_probs[stage]:.6f}",
                f"{results.carry_z_scores[stage]:.6f}",
            ]
            for stage in range(WIDTH + 1)
        ],
    )
    write_csv_table(
        output_dir / "input_probability_summary.csv",
        ["signal", "empirical_probability", "theoretical_probability"],
        [
            ["Cin", f"{results.p_cin_empirical:.6f}", "0.500000"],
            ["A_mean", f"{results.empirical_a_probs.mean():.6f}", "0.500000"],
            ["B_mean", f"{results.empirical_b_probs.mean():.6f}", "0.500000"],
        ],
    )
    write_csv_table(
        output_dir / "conditional_carry_comparison.csv",
        ["condition", "theoretical_probability", "empirical_probability", "z_score", "count"],
        [
            ["P(C_out=1 | C_in=0)", "0.250000", f"{results.p_cout_given_c0:.6f}", f"{results.z_c0:.6f}", results.n_c0],
            ["P(C_out=1 | C_in=1)", "0.750000", f"{results.p_cout_given_c1:.6f}", f"{results.z_c1:.6f}", results.n_c1],
        ],
    )
    write_csv_table(
        output_dir / "summary_metrics.csv",
        ["metric", "value"],
        [
            ["sample_count", results.sample_count],
            ["functional_mismatches", results.functional_mismatches],
            ["expected_mismatches", results.expected_mismatches],
            ["sigma_threshold", f"{results.sigma_threshold:.6f}"],
            ["model_valid", str(results.model_valid)],
        ],
    )
    write_csv_table(
        output_dir / "sum_absolute_error.csv",
        ["bit", "absolute_error"],
        [[bit, f"{results.sum_absolute_errors[bit]:.6f}"] for bit in range(WIDTH)],
    )
    write_csv_table(
        output_dir / "carry_absolute_error.csv",
        ["stage", "absolute_error"],
        [[carry_labels[stage], f"{results.carry_absolute_errors[stage]:.6f}"] for stage in range(WIDTH + 1)],
    )

    create_line_plot_svg(
        output_dir / "sum_probability_comparison.svg",
        "Sum Bit Probability: Theoretical vs Empirical",
        bit_labels,
        results.theoretical_sum_probs.tolist(),
        results.empirical_sum_probs.tolist(),
        "P(S_i = 1)",
    )
    create_line_plot_svg(
        output_dir / "carry_probability_comparison.svg",
        "Carry Probability by Stage: Theoretical vs Empirical",
        carry_labels,
        results.theoretical_carry_probs.tolist(),
        results.empirical_carry_probs.tolist(),
        "P(C_i = 1)",
    )
    create_line_plot_svg(
        output_dir / "input_bit_probability_A.svg",
        "Input A Bit Probabilities",
        bit_labels,
        [0.5] * WIDTH,
        results.empirical_a_probs.tolist(),
        "P(A_i = 1)",
    )
    create_line_plot_svg(
        output_dir / "input_bit_probability_B.svg",
        "Input B Bit Probabilities",
        bit_labels,
        [0.5] * WIDTH,
        results.empirical_b_probs.tolist(),
        "P(B_i = 1)",
    )
    create_bar_plot_svg(
        output_dir / "conditional_carry_probabilities.svg",
        "Conditional Carry Transition Probabilities",
        ["C_in = 0", "C_in = 1"],
        [0.25, 0.75],
        [results.p_cout_given_c0, results.p_cout_given_c1],
        "P(C_out = 1 | condition)",
    )
    create_single_series_bar_plot_svg(
        output_dir / "sum_absolute_error.svg",
        "Absolute Error in Sum Bit Probabilities",
        bit_labels,
        results.sum_absolute_errors.tolist(),
        "|Empirical - Theoretical|",
    )
    create_single_series_bar_plot_svg(
        output_dir / "carry_absolute_error.svg",
        "Absolute Error in Carry Probabilities",
        carry_labels,
        results.carry_absolute_errors.tolist(),
        "|Empirical - Theoretical|",
    )
    create_histogram_svg(
        output_dir / "sum_value_histogram.svg",
        "Histogram of DUT Sum[15:0] Values",
        results.sum_values,
        bins=32,
        x_label="Sum value",
    )
    create_histogram_svg(
        output_dir / "input_A_histogram.svg",
        "Histogram of Input A Values",
        results.a_values,
        bins=32,
        x_label="A value",
        bar_color="#4b6cb7",
    )
    create_histogram_svg(
        output_dir / "input_B_histogram.svg",
        "Histogram of Input B Values",
        results.b_values,
        bins=32,
        x_label="B value",
        bar_color="#8a5a44",
    )
    create_histogram_svg(
        output_dir / "total_output_histogram.svg",
        "Histogram of 17-bit Total Output Values",
        results.dut_totals,
        bins=40,
        x_label="Total output value",
        bar_color="#7a4eab",
    )
    create_histogram_svg(
        output_dir / "cin_histogram.svg",
        "Histogram of Carry-In Samples",
        results.cin_values,
        bins=2,
        x_label="Cin",
        bar_color="#ad7c2b",
    )


def analyze_samples(samples: List[Sample], sigma_threshold: float) -> AnalysisResults:
    if not samples:
        raise ValueError("No complete samples were recovered from the VCD.")

    a_values = np.array([sample.a for sample in samples], dtype=np.uint32)
    b_values = np.array([sample.b for sample in samples], dtype=np.uint32)
    cin_values = np.array([sample.cin for sample in samples], dtype=np.uint8)
    sum_values = np.array([sample.sum_value for sample in samples], dtype=np.uint32)
    cout_values = np.array([sample.cout for sample in samples], dtype=np.uint8)
    expected_totals = np.array([sample.expected_total for sample in samples], dtype=np.uint32)

    recomputed_totals = a_values.astype(np.uint32) + b_values.astype(np.uint32) + cin_values.astype(np.uint32)
    dut_totals = (cout_values.astype(np.uint32) << WIDTH) | sum_values.astype(np.uint32)
    functional_mismatches = int(np.count_nonzero(dut_totals != recomputed_totals))
    expected_mismatches = int(np.count_nonzero(expected_totals != recomputed_totals))

    a_bits = extract_bit_matrix(a_values, WIDTH)
    b_bits = extract_bit_matrix(b_values, WIDTH)
    sum_bits = extract_bit_matrix(sum_values, WIDTH)

    carry_matrix = np.array(
        [reconstruct_internal_carries(sample.a, sample.b, sample.cin, WIDTH) for sample in samples],
        dtype=np.int8,
    )

    theoretical_carry_profile = np.array(carry_probability_profile(WIDTH, 0.5))
    theoretical_sum_probs = np.full(WIDTH, 0.5, dtype=np.float64)
    empirical_a_probs = a_bits.mean(axis=0)
    empirical_b_probs = b_bits.mean(axis=0)
    empirical_sum_probs = sum_bits.mean(axis=0)
    empirical_carry_probs = carry_matrix.mean(axis=0)
    sum_absolute_errors = np.abs(empirical_sum_probs - theoretical_sum_probs)
    carry_absolute_errors = np.abs(empirical_carry_probs - theoretical_carry_profile)

    print("=== Dataset Summary From VCD ===")
    print(f"Recovered samples: {len(samples)}")
    print(f"Functional mismatches between DUT output and software model: {functional_mismatches}")
    print(f"Mismatches between VCD expected_total and software model: {expected_mismatches}")
    print()

    print("=== Input Randomness Sanity Check ===")
    print(f"P(Cin=1): empirical={cin_values.mean():.4f}, expected=0.5000")
    print(
        f"Mean P(A_i=1): empirical={empirical_a_probs.mean():.4f}, expected=0.5000, "
        f"max bit deviation={np.max(np.abs(empirical_a_probs - 0.5)):.4f}"
    )
    print(
        f"Mean P(B_i=1): empirical={empirical_b_probs.mean():.4f}, expected=0.5000, "
        f"max bit deviation={np.max(np.abs(empirical_b_probs - 0.5)):.4f}"
    )
    print()

    print("=== Sum-Bit Validation ===")
    sum_z_scores = np.zeros(WIDTH, dtype=np.float64)
    max_sum_z = 0.0
    for bit in range(WIDTH):
        observed = float(empirical_sum_probs[bit])
        z_score = bernoulli_z_score(observed, 0.5, len(samples))
        sum_z_scores[bit] = z_score
        max_sum_z = max(max_sum_z, abs(z_score))
        print(f"Bit {bit:2d}: empirical={observed:.4f}, expected=0.5000, z={z_score:+.2f}")
    print()

    print("=== Carry-State Validation ===")
    carry_z_scores = np.zeros(WIDTH + 1, dtype=np.float64)
    max_carry_z = 0.0
    for stage in range(WIDTH + 1):
        observed = float(empirical_carry_probs[stage])
        expected = float(theoretical_carry_profile[stage])
        z_score = bernoulli_z_score(observed, expected, len(samples))
        carry_z_scores[stage] = z_score
        max_carry_z = max(max_carry_z, abs(z_score))
        label = "Cin" if stage == 0 else f"C{stage}"
        print(f"{label:>3}: empirical={observed:.4f}, expected={expected:.4f}, z={z_score:+.2f}")
    print()

    c_in = carry_matrix[:, :-1]
    c_out = carry_matrix[:, 1:]
    mask_c0 = c_in == 0
    mask_c1 = c_in == 1
    n_c0 = int(mask_c0.sum())
    n_c1 = int(mask_c1.sum())

    p_cout_given_c0 = float(c_out[mask_c0].mean()) if n_c0 else float("nan")
    p_cout_given_c1 = float(c_out[mask_c1].mean()) if n_c1 else float("nan")
    z_c0 = bernoulli_z_score(p_cout_given_c0, 0.25, n_c0)
    z_c1 = bernoulli_z_score(p_cout_given_c1, 0.75, n_c1)

    print("=== Conditional Carry Transition Validation ===")
    print(f"P(C_out=1 | C_in=0): empirical={p_cout_given_c0:.4f}, expected=0.2500, z={z_c0:+.2f}, N={n_c0}")
    print(f"P(C_out=1 | C_in=1): empirical={p_cout_given_c1:.4f}, expected=0.7500, z={z_c1:+.2f}, N={n_c1}")
    print()

    validity_checks = [
        functional_mismatches == 0,
        expected_mismatches == 0,
        max_sum_z <= sigma_threshold,
        max_carry_z <= sigma_threshold,
        abs(z_c0) <= sigma_threshold,
        abs(z_c1) <= sigma_threshold,
    ]
    model_valid = all(validity_checks)

    print("=== Final Verdict ===")
    if model_valid:
        print(
            "The VCD data is consistent with the ripple-carry probabilistic model "
            f"within a {sigma_threshold:.1f} sigma acceptance band."
        )
    else:
        print(
            "The VCD data does not fully validate the ripple-carry probabilistic model "
            f"under the current {sigma_threshold:.1f} sigma acceptance band."
        )

    return AnalysisResults(
        sample_count=len(samples),
        functional_mismatches=functional_mismatches,
        expected_mismatches=expected_mismatches,
        a_values=a_values,
        b_values=b_values,
        cin_values=cin_values,
        sum_values=sum_values,
        dut_totals=dut_totals,
        empirical_a_probs=empirical_a_probs,
        empirical_b_probs=empirical_b_probs,
        empirical_sum_probs=empirical_sum_probs,
        empirical_carry_probs=empirical_carry_probs,
        theoretical_sum_probs=theoretical_sum_probs,
        theoretical_carry_probs=theoretical_carry_profile,
        sum_absolute_errors=sum_absolute_errors,
        carry_absolute_errors=carry_absolute_errors,
        sum_z_scores=sum_z_scores,
        carry_z_scores=carry_z_scores,
        p_cin_empirical=float(cin_values.mean()),
        p_cout_given_c0=p_cout_given_c0,
        p_cout_given_c1=p_cout_given_c1,
        z_c0=z_c0,
        z_c1=z_c1,
        n_c0=n_c0,
        n_c1=n_c1,
        model_valid=model_valid,
        sigma_threshold=sigma_threshold,
    )


def main() -> None:
    args = parse_args()
    resolved_vcd_path = resolve_vcd_path(args.vcd)
    output_dir = args.output_dir
    if not output_dir.is_absolute():
        output_dir = SCRIPT_DIR / output_dir

    print_probabilistic_model(WIDTH, 0.5)
    print(f"Using VCD file: {resolved_vcd_path}")
    print(f"Writing analysis outputs to: {output_dir}")
    print()

    samples = parse_vcd_samples(resolved_vcd_path)
    if len(samples) != args.num_samples:
        print(
            f"Warning: expected {args.num_samples} samples, but recovered {len(samples)} complete samples "
            f"from {resolved_vcd_path}."
        )
        print()
    results = analyze_samples(samples, args.sigma_threshold)
    write_analysis_outputs(output_dir, results)
    print()
    print("=== Output Files ===")
    print(output_dir / "summary_metrics.csv")
    print(output_dir / "input_probability_summary.csv")
    print(output_dir / "sum_bit_comparison.csv")
    print(output_dir / "carry_probability_comparison.csv")
    print(output_dir / "conditional_carry_comparison.csv")
    print(output_dir / "sum_probability_comparison.svg")
    print(output_dir / "carry_probability_comparison.svg")
    print(output_dir / "input_bit_probability_A.svg")
    print(output_dir / "input_bit_probability_B.svg")
    print(output_dir / "conditional_carry_probabilities.svg")
    print(output_dir / "sum_absolute_error.csv")
    print(output_dir / "carry_absolute_error.csv")
    print(output_dir / "sum_absolute_error.svg")
    print(output_dir / "carry_absolute_error.svg")
    print(output_dir / "sum_value_histogram.svg")
    print(output_dir / "input_A_histogram.svg")
    print(output_dir / "input_B_histogram.svg")
    print(output_dir / "total_output_histogram.svg")
    print(output_dir / "cin_histogram.svg")


if __name__ == "__main__":
    main()
